### ISSUE TITLE
crash when mkfs.ext4 on nbd volume

### ISSUE THREAD

**Issue by sokoow** [coreos/torus#240] opened 2016-06-07 16:43 UTC
I got a following crash when initializing an empty volume, pretty much all the time torusd is starting:

```
2016-06-07 16:42:06.726872 I | torus: creating metadata service: etcd
2016-06-07 16:42:06.748510 I | torus: 530c28ef-2cce-11e6-9c5e-00163e425a18: 1
2016-06-07 16:42:06.748888 I | torus: creating blockstore: mfile
2016-06-07 16:42:06.749034 I | storage: loading block index...
2016-06-07 16:42:06.749524 I | storage: done loading block index
2016-06-07 16:42:06.759902 I | torus: 530c28ef-2cce-11e6-9c5e-00163e425a18: 1
panic: runtime error: slice bounds out of range

goroutine 87 [running]:
panic(0xc05d80, 0xc8200100a0)
        /usr/lib/go-1.6/src/runtime/panic.go:464 +0x3e6
github.com/coreos/torus/distributor.(*Distributor).GetBlock(0xc8201d7320, 0x7f39a1752948, 0xc82035d110, 0x10000000003, 0x5, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /opt/go/src/github.com/coreos/torus/distributor/storage.go:35 +0xeac
github.com/coreos/torus.(*INodeStore).GetINode(0xc8202e22c0, 0x7f39a1752948, 0xc82035d110, 0x3, 0x5, 0x1, 0x0, 0x0)
        /opt/go/src/github.com/coreos/torus/inode.go:94 +0x1a3
github.com/coreos/torus/block.(*blockvolGC).PrepVolume(0xc8202c4600, 0xc82035c810, 0x0, 0x0)
        /opt/go/src/github.com/coreos/torus/block/gc_block_vol.go:70 +0x7ac
github.com/coreos/torus/gc.(*controller).PrepVolume(0xc8202e22e0, 0xc82035c810, 0x0, 0x0)
        /opt/go/src/github.com/coreos/torus/gc/gc.go:46 +0xcb
github.com/coreos/torus/distributor/rebalance.(*rebalancer).PrepVolume(0xc8202c92c0, 0xc82035c810, 0x0, 0x0)
        /opt/go/src/github.com/coreos/torus/distributor/rebalance/rebalancer.go:56 +0x50
github.com/coreos/torus/distributor.(*Distributor).rebalanceTicker(0xc8201d7320, 0xc8202c9320)
        /opt/go/src/github.com/coreos/torus/distributor/rebalance.go:55 +0x27c
created by github.com/coreos/torus/distributor.newDistributor
        /opt/go/src/github.com/coreos/torus/distributor/distributor.go:69 +0x8fe
```

**Comment by sokoow** [comment] 2016-06-07 16:55
It seems to only happen when it's running on a single node

**Comment by mdlayher** [comment] 2016-06-08 22:53
Possibly related to: https://github.com/coreos/torus/issues/219.

**Comment by dongsupark** [comment] 2016-06-11 09:19
Right. I stumbled across this issue too. Following the instructions from https://github.com/coreos/torus/blob/master/Documentation/getting-started.md, it's quite easy to trigger the panic. And it seems to happen only with a single node.

**Comment by barakmich** [comment] 2016-06-13 20:15
Yep. Marking this as a duplicate of #219

**Closed by barakmich** 2016-06-13 20:15 UTC
Labels: reviewed/duplicate
